### ISSUE TITLE
No SPC m commands available after install

### ISSUE THREAD

**Issue by dclausen** [brantou/spacemacs-crystal-layer#1]
I performed the following:

- git clone git@github.com:brantou/spacemacs-crystal-layer.git ~/.emacs.d/private/crystal
- added crystal to dotspacemacs-configuration-layers
- restarted Spacemacs

When I open a .cr file, I see the syntax highlighting but none of the SPC m commads are available to use.

I'm running 0.200.10@25.3.1 installed via Homebrew on MacOS High Sierra.

**Comment by brantou** [comment]
@dclausen  Spacemacs on develop branch?

**Comment by dclausen** [comment]
Sorry, not sure what you're asking. Did you want to know if I installed Spacemacs using the develop branch, or should I try the latest Spacemacs develop branch to see if that fixes the issue?

**Comment by brantou** [comment]
If you installed Spacemacs using the develop branch, you need this:

`git clone -b develop https://github.com/brantou/spacemacs-crystal-layer.git ~/.emacs.d/private/crystal`

**Comment by brantou** [comment]
@dclausen Sorry, my English is not good.
