### ISSUE TITLE
Ameba linter integration

### ISSUE THREAD

**Issue by veelenga** [brantou/spacemacs-crystal-layer#3]
[Ameba](https://github.com/veelenga/ameba) is a static code analysis tool for Crystal.
[Ameba.el](https://github.com/veelenga/ameba.el) is an Emacs interface to Ameba.

Would you mind to integrate ameba.el into the spacemacs-crystal-layer?

**Comment by brantou** [comment]
@veelenga Integrate ameba.el into the spacemacs-crystal-layer by https://github.com/brantou/spacemacs-crystal-layer/commit/464bb4e3969b4fcbeaf7f0260b40a958eb0c4c7c

**Comment by veelenga** [comment]
Wow, that was quick. Thank you, will test it.
